### ISSUE TITLE
这个工具好像要消耗fofa的那个币......试着搜了下，扣了好几个

### ISSUE THREAD

**Issue by YangSirrr** [ja9er/Gofreeproxy#1]
如题

**Comment by ja9er** [comment]
![图片](https://user-images.githubusercontent.com/87508014/192222031-833f4eed-5086-46ae-88cf-6b6dc261a414.png)
我是0个也可以用，是账户的问题。
![图片](https://user-images.githubusercontent.com/87508014/192222644-6f277719-5b38-4bcf-9211-893faedb1c44.png)
如果是注册用户使用API导出的数据就需要扣除F币。你可以修改maxpage，或者在源码fofaall函数中修改对应的数量限制以避免扣除F币

**Comment by YangSirrr** [comment]
明白了谢谢，我研究下
