### ISSUE TITLE
获取代理为0条？

### ISSUE THREAD

**Issue by gitffm** [ja9er/Gofreeproxy#15]
![image](https://user-images.githubusercontent.com/120312739/206902318-57036056-c95e-44fe-9735-fe85c60f9fa2.png)
一直卡在这里

**Comment by win1498419293** [comment]
+1也是这个问题，我猜测可能是fofa需要会员或者api次数的原因，只能坐等大佬解答了

**Comment by ja9er** [comment]
1.检查你的会员账号关于APi的限制 config.ini 中maxpage*1000 要小于这个限制
刚刚测的这个release版本是没有问题的
![图片](https://user-images.githubusercontent.com/87508014/206998977-684cb143-e318-4902-9ea4-d50889c0144e.png)
