### ISSUE TITLE
在MAC m1上运行出错了，是什么原因了，在虚拟机windows也是一样的

### ISSUE THREAD

**Issue by zkj123** [ja9er/Gofreeproxy#19]
<img width="294" alt="image" src="https://user-images.githubusercontent.com/10055194/209762158-9de727f5-c391-43e1-89fb-f4cf01a2c7cc.png">
在MAC m1上运行出错了，是什么原因了，在虚拟机windows也是一样的

**Comment by ja9er** [comment]
已修复，新版代码
