### ISSUE TITLE
收集后的代理不会写入proxy.txt

### ISSUE THREAD

**Issue by pluto-ctrl** [ja9er/Gofreeproxy#2]

**Comment by pluto-ctrl** [comment]
<img width="568" alt="image" src="https://user-images.githubusercontent.com/69779230/192490598-a652ac41-7647-4288-81fe-1016b62e7955.png">
<img width="290" alt="image" src="https://user-images.githubusercontent.com/69779230/192490712-0e95884b-3c74-4dcd-9d8d-e3219f029946.png">
显示没有代理可以用

**Comment by pluto-ctrl** [comment]
大佬，已经解决了，在windows用没问题，mac可能因为函数问题写不进去

**Comment by zkj123** [comment]
<img width="293" alt="image" src="https://user-images.githubusercontent.com/10055194/209763417-3a6e9482-f782-49b5-a944-bd64cc724573.png">

**Comment by zkj123** [comment]
有解决方案嘛？

**Comment by yangyang5214** [comment]
@zkj123 当前目录没有 config.ini 文件配置。你从项目最外部 copy 一份到 二进制文件目录。
