### ISSUE TITLE
控制台输出未覆盖完全

### ISSUE THREAD

**Issue by k-fire** [ja9er/Gofreeproxy#6]
第一条输出：[+]当前使用代理127.0.0.1:111100000
第二条输出：[+]当前使用代理127.0.0.1:5555
最终效果：    [+]当前使用代理127.0.0.1:555500000
如果前一条输出字符长度大于后一条字符输出长度，则会造成显示异常
参考演示图片：
![image](https://github.com/ja9er/Gofreeproxy/raw/master/image/goproxy.gif)

**Comment by ja9er** [comment]
已修复
